// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9vsv7zY31IEmBEsyphmWAU0F2w-zS_EY',
    appId: '1:753832950795:web:99e76e8141cb2dcb081b0e',
    messagingSenderId: '753832950795',
    projectId: 'chat-app-3d210',
    authDomain: 'chat-app-3d210.firebaseapp.com',
    storageBucket: 'chat-app-3d210.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKEn-lQXQ_TtyNySTVYopRvDHv1effRZQ',
    appId: '1:753832950795:android:a1b7e2d6d6611734081b0e',
    messagingSenderId: '753832950795',
    projectId: 'chat-app-3d210',
    storageBucket: 'chat-app-3d210.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcJ-BQchwU3BHNxWBIfevkSyFItb4kz2w',
    appId: '1:753832950795:ios:40df91138b202d2a081b0e',
    messagingSenderId: '753832950795',
    projectId: 'chat-app-3d210',
    storageBucket: 'chat-app-3d210.appspot.com',
    iosBundleId: 'com.example.minimalChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcJ-BQchwU3BHNxWBIfevkSyFItb4kz2w',
    appId: '1:753832950795:ios:7314b504b1d54dae081b0e',
    messagingSenderId: '753832950795',
    projectId: 'chat-app-3d210',
    storageBucket: 'chat-app-3d210.appspot.com',
    iosBundleId: 'com.example.minimalChatApp.RunnerTests',
  );
}
